
import { CategoryType, CategoryMetadata } from './types';

export const CATEGORIES: CategoryMetadata[] = [
  { type: CategoryType.ICE_BREAKERS, color: 'bg-[#FDFBF7] border-[#1A231C]/20 text-[#1A231C]', icon: '🗝️', description: 'The Sunlit Path. Gentle queries to begin the stroll.', image: '/src/assets/images/light_tarot_key_1782337499866.jpg' },
  { type: CategoryType.PREFERENCES, color: 'bg-[#F9F6F0] border-[#1A231C]/20 text-[#1A231C]', icon: '⏳', description: 'The Peculiar Garden. Mapping the beautiful geometry of desires.', image: '/src/assets/images/light_tarot_hourglass_1782337510092.jpg' },
  { type: CategoryType.CONNECTION, color: 'bg-[#FDFBF7] border-[#1A231C]/20 text-[#1A231C]', icon: '🌸', description: 'Blooming Roots. Tending to the vines that intertwine us.', image: '/src/assets/images/light_quirky_heart_1782337831795.jpg' },
  { type: CategoryType.FANTASY, color: 'bg-[#F9F6F0] border-[#1A231C]/20 text-[#1A231C]', icon: '👁️', description: 'Clouds & Chimeras. Curious visions and soaring reveries.', image: '/src/assets/images/light_tarot_eye_1782337485791.jpg' },
  { type: CategoryType.KNOTS, color: 'bg-[#FDFBF7] border-[#8a1c1c]/30 text-[#1A231C]', icon: '🎀', description: 'Silk & Thorns. The delightful dance of restraint and release.', image: '/src/assets/images/light_tarot_ribbons_1782337521250.jpg' },
  { type: CategoryType.TABOO, color: 'bg-[#F9F6F0] border-[#1A231C]/20 text-[#1A231C]', icon: '🪞', description: 'The Secret Glade. Reflections from the sun-dappled shadows.', image: '/src/assets/images/light_tarot_mirror_1782337531717.jpg' },
  { type: CategoryType.SCENARIOS, color: 'bg-[#FDFBF7] border-[#1A231C]/20 text-[#1A231C]', icon: '🎭', description: 'Theatrical Fancies. Playful masquerades and hypothetical trysts.', image: '/src/assets/images/light_quirky_mask_1782337864414.jpg' },
  { type: CategoryType.DEEP_DIVE, color: 'bg-[#F9F6F0] border-[#1A231C]/20 text-[#1A231C]', icon: '🌙', description: 'The Inner Sky. Ascending into the profound and the raw.', image: '/src/assets/images/light_tarot_moon_1782337561219.jpg' },
  { type: CategoryType.CURIOUS_MINDS, color: 'bg-[#FDFBF7] border-[#1A231C]/20 text-[#1A231C]', icon: '🔮', description: 'Intimate Mindscapes. Exploring the curious landscapes of thought and memory.', image: '/src/assets/images/light_tarot_spread_1782337571950.jpg' },
];

export const RAW_CARDS: Record<CategoryType, string[]> = {
  [CategoryType.ICE_BREAKERS]: [
    "What is the most attractive non-physical trait I have?",
    "If we had a completely free weekend with no responsibilities, what would we do?",
    "What was your very first impression of me?",
    "What is a silly habit of mine that you secretly love?",
    "When did you first realize you were attracted to me?",
    "What is your favorite memory of us together?",
    "What outfit of mine do you love the most?",
    "If you could teleport us anywhere in the world right now, where would we go?",
    "What is the best compliment you've ever received from me?",
    "What is one thing you've always wanted to ask me but haven't?",
    "Whats something you want to do in the next year together with someone?",
    "If we were handed an unexpected $50,000 grant to spend entirely on a shared adventure, passion project, or lifestyle upgrade, how exactly would we allocate it?",
    "What does your absolute ideal retirement lifestyle look like with me? Where in the world are we living, and what constitutes a perfect, mundane Tuesday?",
    "If we could take a six-month sabbatical together anywhere in the world, what country would we move to, and what would our daily routine consist of?",
    "What is a hobby, physical skill, or foreign language you have always wanted to learn that we could start taking local classes for together this year?",
    "If we were given unlimited funds to design and build our dream house from scratch, what is one wildly specific, non-negotiable architectural feature we would include?",
    "What is a major bucket-list destination you want us to travel to in the next five years, and what is the very first meal or activity we would experience there?",
    "What is a shared legacy, tradition, or philanthropic impact you want us to leave on our friends, family, or community as a couple?",
    "If we could adopt any radical lifestyle shift next month (e.g., waking at 5 AM, going entirely plant-based, instituting no-screen evenings), what should we experiment with?",
    "What is an adventure, road trip, or specific date we've already taken that you would love to recreate or do a \"Part 2\" of because it was so perfect?",
    "How do you envision the next three years of our lives? What is a major professional or personal milestone you hope we are celebrating together?",
    "What is a positive habit or joyful dynamic in our current relationship that you want to actively, fiercely protect so it never changes, even if we have kids or move?",
    "If we were forced to start a side-hustle or a creative business together tomorrow, what would the company do, and who would be the CEO versus the creative director?",
    "What is a personal, individual dream of yours for the upcoming year that I can actively help you support, fund, or achieve without taking it over?",
    "If we could spend an entire month living completely off the grid in a cabin with no internet or cell service, how do you think it would alter our relationship?",
    "What is a deeply meaningful holiday tradition from your own childhood that you absolutely want us to implement in our own home moving forward?",
    "If we had to relocate to a new city where we knew absolutely no one, what would be our strategy for building a new social circle and a new life together?",
    "What is a practical fear you have about the future that you think we need to actively prepare for as a team, rather than ignoring it?",
    "If we could co-author a book together based on our experiences, what would the subject matter be, and what would the title be?",
    "Fast forward to our 50th wedding anniversary. What do you want the toast that our closest friends and family give about us to highlight?",
    "If we were forced to compete as a duo on a reality television survival show, what would be our greatest strength, and what petty argument would cause our downfall?",
    "If you were suddenly granted the ability to read my mind, but only for exactly five minutes a day, what specific time of day would you choose to tune in?",
    "If our relationship was a massive corporation and had a \"mission statement\" or a ridiculous marketing slogan, what would it be?",
    "We have been cursed by a swamp witch and must magically swap bodies for a week. What is the very first thing you are going to do while piloting my body?",
    "If major global cities were people, who would be your brief, chaotic summer fling, who would be your reliable partner, and who would be your toxic ex?",
    "If you had to select one mundane, daily household task that I would be legally required to do for you for the rest of our lives, what would you choose?",
    "We are forming an eccentric two-person musical band. What highly specific genre of music do we play, what are our stage names, and who is the demanding lead diva?",
    "If every time I entered a room, a specific theme song played out loud from the heavens, what song would perfectly capture my essence?",
    "If we were both arrested for a completely ridiculous, non-violent crime, what would our friends and family immediately assume we were caught doing?",
    "You have to give a 30-minute TED Talk right now to a stadium of people with zero preparation. What hyper-specific, obscure topic are you speaking about?",
    "If we had to survive a fast-moving zombie apocalypse together, what is our weapon of choice, and what is our primary survival strategy for finding food?",
    "If you could instantly download three master-level skills into your brain Matrix-style, what would they be, and how would you use them to impress me?",
    "We are given the chance to time travel to any era for exactly one week. Where do we go, what do we wear, and what historical event do we accidentally interfere with?",
    "If you were forced to eat only one meal cooked by me for the rest of your life, what specific dish are you choosing to never get sick of?",
    "If you could magically change one minor, harmless annoyance about my daily habits without me ever noticing, what would you selectively edit out?",
    "We have to open a highly niche, absurdly specific retail store in a trendy neighborhood. What do we sell, and what is the target demographic?",
    "If you had to describe my personality using only specific types of food, spices, or flavor profiles, what would I be?",
    "If we were secretly superheroes, what would our deeply unimpressive, mildly convenient, but ultimately useless superpowers be?",
    "You are allowed to ask me one question right now that I must answer with 100% absolute truth, bound by magic. What do you ask?",
    "If our pets (or future imaginary pets) could talk, what would be the number one complaint or piece of gossip they have about our relationship dynamics?"
  ],
  [CategoryType.PREFERENCES]: [
    "Do you prefer morning, afternoon, or late-night intimacy?",
    "What is your favorite place to be touched?",
    "How important is dirty talk to you on a scale of 1 to 10?",
    "Do you like it when I take charge, or do you prefer to lead?",
    "What is a specific physical feature of mine that turns you on?",
    "Do you enjoy slow, sensual intimacy or fast, rough passion?",
    "What is your stance on public displays of affection?",
    "How do you feel about introducing toys into the bedroom?",
    "What kind of foreplay drives you absolutely crazy?",
    "Do you like visual stimulation (like watching in a mirror or keeping the lights on)?",
    "What is a specific, non-sexual touch of mine that instantly makes your body feel relaxed, grounded, and open to intimacy?",
    "Describe the exact moment in our relationship's history when you felt the most overwhelming surge of raw sexual tension between us.",
    "When you look at my body during moments of intimacy, where does your gaze naturally linger the longest, and what thoughts cross your mind?",
    "If you could isolate one highly specific physical sensation that I provide—such as the way I kiss your neck or trace your spine—what would you ask for more often?",
    "What is your absolute favorite sensory memory of the very first time we were physically intimate together?",
    "How does intense eye contact during intercourse affect your arousal? Does it make you feel more deeply connected, or do you find it psychologically overwhelming?",
    "Describe the perfect sensory environment for our next intimate encounter. What is the precise lighting, the temperature of the room, and the background sound?",
    "What is a scent, an article of clothing, or a physical aesthetic of mine that you find irresistibly attractive, even if you rarely mention it?",
    "Do you tend to crave physical intimacy more when you are stressed and seeking comfort, or when you are deeply relaxed and seeking play?",
    "If I were to dedicate an entire hour to kissing you without it leading to intercourse, how and where on your body would you want me to start? And more importantly, what motivation do you need to take my entire thick cock down your throat afterwards?",
    "What is the most sensitive erotic zone on your body that you feel we currently under-utilize or ignore during foreplay?",
    "What physical cue or micro-expression do you unconsciously give when you are highly aroused but haven't explicitly stated it yet?",
    "Describe a time when you were deeply turned on by something completely unexpected or unconventional that I did in a non-sexual setting.",
    "If you could choose one specific outfit, piece of lingerie, or style for me to wear to bed tonight, what exactly would it look like?",
    "What is your preferred pacing for physical intimacy? Do you prefer a slow, agonizing, teasing buildup, or spontaneous, intense passion?",
    "How do you define the psychological difference between sensuality and sexuality, and which of the two do you feel we need more of right now?",
    "What is a specific song, artist, or genre of music that always makes you think of me in a deeply sensual or erotic context?",
    "When we are navigating a public setting or a social gathering, what subtle physical gesture from me makes you anticipate getting home together?",
    "What is your favorite physical memory of us from a vacation, a hotel stay, or a location entirely outside of our own bedroom?",
    "If you could describe my unique \"kissing signature\" or physical rhythm in three highly descriptive words, what would they be?"
  ],
  [CategoryType.CONNECTION]: [
    "What is something I do that makes you feel incredibly loved?",
    "When do you feel the most deeply connected to me?",
    "What is a vulnerability you feel safe sharing with me?",
    "How can I better support you when you're feeling stressed?",
    "What is a goal or dream you have for our relationship?",
    "What makes you feel truly seen and understood by me?",
    "How do you define intimacy outside of the bedroom?",
    "What is a boundary you have that you feel is highly respected?",
    "In what ways have we grown together since we met?",
    "What is your favorite non-sexual physical touch we share?",
    "What is a small, quiet, seemingly insignificant moment from this past week where you felt an unexpected wave of profound love and gratitude for me?",
    "If you had to describe our current relationship dynamic as a weather forecast (e.g., partly cloudy with sudden warmth, or a steady gentle breeze), what would it be and why?",
    "What is an \"unofficial resume\" skill of mine—something I am uniquely brilliant at but would never put on a professional document—that you admire deeply?",
    "If you could magically steal one personality trait, habit, or psychological strength of mine and make it your own, what would it be?",
    "Describe the exact moment you realized you were falling in love with me. What was the physical setting, and what shifted internally for you in that second?",
    "If our love story was categorized into a movie genre, would it be a chaotic indie comedy, a high-stakes adventure, a cozy domestic drama, or a fantasy epic? Why?",
    "What is a meaningful compliment regarding my character or growth that you have been holding back or simply forgot to articulate to me recently?",
    "What is a specific childhood memory of yours that you feel perfectly explains why you react the way you do to conflict or affection in our relationship today?",
    "If we were to commission a piece of abstract art that perfectly represents the energy and history of our relationship, what colors, textures, and shapes would it feature?",
    "What is a deep, introspective question you wish I would ask you more often about your inner world, your ambitions, or your daily mental state?",
    "How do you think we have grown, evolved, or matured as a unit since the very first month we started dating? What childish habits did we leave behind?",
    "What is a small, everyday habit or domestic routine of mine that makes you feel completely safe, anchored, and at home, no matter how chaotic life gets?",
    "If you could retroactively erase one past disagreement we had, which one would it be, and how would we handle it with the communication tools we have now?",
    "What is a major stressor or background worry you are currently carrying that you haven't fully unburdened onto me yet, perhaps because you don't want to worry me?",
    "What are three distinct things you are deeply proud of regarding who I am as an individual, entirely separate from my role as your romantic partner?",
    "Who was your childhood hero (real or fictional), and what qualities of theirs do you find yourself actively looking for in the people you surround yourself with today?",
    "When we face external adversity as a team—like a financial crisis, a family issue, or a travel disaster—what is the specific dynamic that makes us so resilient?",
    "If you were asked to describe the defining \"philosophy\" or core ethos of our relationship to a complete stranger, what would you say?",
    "What is a piece of advice your younger self desperately needed regarding love, attachment, or self-worth that you finally understand now?",
    "How do you define the concept of unconditional love, and in what specific, tangible moments have you felt it radiating from me?"
  ],
  [CategoryType.FANTASY]: [
    "What is a wild fantasy you've always had but never acted on?",
    "If we could safely act out any scenario with no consequences, what would it be?",
    "Have you ever fantasized about us in a public or risky place? Where?",
    "What is a movie or book scene you've wanted to recreate with me?",
    "How do you feel about the idea of being watched?",
    "Have you ever had a dream about me that you woke up turned on from?",
    "What is a taboo fantasy that secretly excites you?",
    "If you could have me dress up as anything for you, what would it be?",
    "What is the dirtiest thought you've had about me today?",
    "How do you feel about the idea of recording ourselves for our own eyes only?",
    "What is a recurring sexual fantasy you have thought about while masturbating that you have never felt comfortable sharing with me until now?",
    "How do you feel about the idea of me watching you satisfy yourself? What makes that concept highly arousing, or conversely, deeply intimidating?",
    "If we were shopping at a high-end adult boutique together right now, what is the very first section, toy, or item you would suggest we examine?",
    "What is the dirtiest, most explicit thing you have ever imagined me whispering into your ear right at the moment of climax, while my huge cock is buried deep inside you?",
    "Describe a highly vivid dream you had about me recently that woke you up feeling completely aroused and desiring connection.",
    "How do you distinguish between a pure fantasy (something arousing to imagine but not act out) and a practical desire (something you actually want us to execute)?",
    "What is a specific location in our home, strictly outside of the bedroom, that you have secretly wanted to \"christen\" with physical intimacy?",
    "Do you find auditory stimulation—such as moans, heavy breathing, or dirty talk—essential to your arousal, or do you prefer quiet, focused intensity?",
    "If you could completely redesign the way I typically initiate sex with you, what would your absolute ideal initiation sequence look like?",
    "What is a sexual scenario you've seen in a film, read in erotica, or heard about that you immediately wished we could safely replicate?",
    "How does my vocalization of pleasure impact your own physical arousal? Do you find my satisfaction more exciting than your own bodily sensations?",
    "If we were to introduce a blindfold into our intimate life tonight, what sense—touch, taste, or sound—would you want me to target and overwhelm first?",
    "What is an instant, absolute turn-on for you that completely overrides your logical brain and instantly puts you in a state of desire?",
    "How do you feel about the concept of voyeurism or mild exhibitionism? Have you ever fantasized about the risk of us almost being caught?",
    "If we had to assign a specific \"theme\" or title to our sex life over the last six months, what would it be, and what should the next theme be?",
    "What is a specific, highly detailed sexual memory from our past that you frequently replay in your mind when you are completely alone?",
    "How do you feel about the idea of recording ourselves during an intimate encounter, assuming we have total trust and delete it immediately afterward?",
    "If you were given a magic wand that instantly removed all societal shame or personal awkwardness from one specific sexual act, what act would you want to try?",
    "What is a subtle, unspoken dynamic in our sex life that you find deeply romantic and connecting, but we never explicitly discuss out loud?",
    "Describe the physical and emotional sensation of your climax using only metaphors related to nature, weather, or cosmic events."
  ],
  [CategoryType.KNOTS]: [
    "Do you lean more towards dominance, submission, or switching?",
    "What is a kink you've always wanted to try but haven't yet?",
    "How do you feel about being restrained or tied up?",
    "Do you enjoy sensation play, like temperature differences or light pain?",
    "What is your hard limit in the bedroom?",
    "How does the idea of edge play or sensory deprivation sound to you?",
    "Do you like it when I leave marks on you, or vice versa?",
    "What is a word or phrase that instantly drops you into a submissive/dominant headspace?",
    "How do you feel about power dynamics outside of the bedroom?",
    "What is a soft kink you enjoy (like hair pulling, biting, etc.)?",
    "How do you feel about playful power dynamics in the bedroom? Would you prefer to surrender control completely to me, or be the one dictating the pace and action?",
    "If we were to incorporate light restraints (like silk ties, blindfolds, or handcuffs) tonight, who would be wearing them, and what would the very first instruction be?",
    "Do you find the idea of light physical edge play—such as hair pulling, spanking, or mild scratching—highly arousing, or do you find it distracting and uncomfortable?",
    "What is a specific scenario where you would love for me to be aggressively dominant, take total control, pin you down without asking permission, and make you worship my massive cock?",
    "If you were to give me an absolute, non-negotiable command in the bedroom right now that I had to follow without question, what would you order me to do?",
    "How do you feel about the concept of \"begging\" or being made to wait for pleasure? Does the psychological tease heighten the eventual climax for you?",
    "If we were to engage in total sensory deprivation—where you are blindfolded, wearing headphones, and cannot use your hands—how would you want me to approach your body?",
    "What is a specific \"dirty\" or playfully degrading phrase or title that you would secretly love to be called in the heat of the moment?",
    "If you were tasked with completely ravishing me, without letting me reciprocate or touch you for 20 straight minutes, what would your strategy be?",
    "How do you feel about temperature play? Would you prefer the sharp shock of an ice cube tracing your spine, or the soothing heat of warm massage oil on your chest?",
    "Have you ever fantasized about being \"caught\" in the act or watched by a silent third party? How does the element of external risk influence your internal arousal?",
    "If we established a firm safe word tonight and decided to push your physical boundaries exactly 10% further than our usual routine, what specific act would we try?",
    "What is a specific piece of kink-adjacent equipment (a collar, a crop, a harness, a specific vibrator) that you are highly curious to experiment with?",
    "In what ways do you secretly enjoy being submissive outside the bedroom? How does surrendering daily decision-making to me affect your general stress levels?",
    "If you were directing a highly explicit, big-budget film starring the two of us, what would the core plot, setting, or dynamic of the main scene be?",
    "How do you feel about the idea of me choosing your clothing, including your underwear, for an entire day before we go out on a date?",
    "What is the most animalistic, primal, or feral urge you have ever felt toward me during an intense, uninhibited intimate encounter?",
    "If we were to roleplay a high-stakes interrogation scene where one of us has to extract a confession from the other using only physical persuasion, how would we ensure cooperation?",
    "Do you find the psychological idea of \"punishment\" or discipline in a controlled, consensual, and loving setting to be an intriguing concept to explore?",
    "If you could temporarily remove one of your own strict boundaries for a single night, just to see what the experience feels like without consequence, which boundary would you drop?"
  ],
  [CategoryType.TABOO]: [
    "What is something you consider taboo that actually turns you on?",
    "Have you ever been attracted to someone you shouldn't have been?",
    "What is your opinion on open relationships or non-monogamy?",
    "Have you ever had a crush on one of my friends?",
    "What is the most inappropriate place you've ever had thoughts about me?",
    "How do you feel about the concept of sharing a partner?",
    "What is a sexual secret you've kept from past partners?",
    "Have you ever been caught in the act?",
    "What is your stance on group play or threesomes?",
    "What is a dirty secret you've never told anyone?",
    "Have you ever imagined me with another person? How did it make you feel?",
    "Is there a boundary you've always kept strictly in place, but secretly want me to push?",
    "What is the most primal or animalistic urge you've felt towards me?",
    "Do you enjoy the idea of us being exhibitionists?",
    "If we were to draft a comprehensive \"Sexual Bucket List\" for the upcoming year, what are the top three non-negotiable items you would add to the top of the list?",
    "What is a specific sex position, angle, or rhythm that we rarely do that you would like to make a staple of our regular weekly routine?",
    "If you could ask me to perform one highly specific, intimate act on you tonight without any hesitation, negotiation, or shyness from me, what would it be? And what will you do to my huge cock in return?",
    "We have an empty house with zero interruptions for the next 24 hours. Map out the ideal timeline of our sexual encounters, from morning coffee to midnight.",
    "What is a completely new location, climate, or city in the world where you want us to travel specifically so we can be physically intimate there?",
    "If we were to purchase a high-end, technologically advanced sex toy together this weekend, what exact function, vibration, or sensation should it provide?",
    "How can we actively make our routine, everyday maintenance sex feel more intentional, passionate, and less like a mechanical domestic habit?",
    "What is one highly specific sentence or photo I can text you in the middle of a mundane workday that will instantly make you wet/hard?",
    "If you had to teach a masterclass to a clone of me on how to perfectly bring you to a mind-blowing climax, what would your step-by-step syllabus look like?",
    "What is a sexual skill, physical technique, or aspect of endurance that you want to actively practice and improve upon for my benefit?",
    "How do you envision our sex life evolving as we age over the next decades? What do you hope we prioritize when our physical bodies inevitably change?",
    "What is a sensual morning ritual we could adopt to ensure we start the day feeling physically connected before we even leave the bed?",
    "If we were to dedicate an entire Sunday to exploring the art of prolonged foreplay and teasing without any intercourse, what activities would be involved?",
    "What is a specific physical compliment or validation you wish I would give you much more frequently when I see you completely naked?",
    "If we had to create a visual \"mood board\" for our desired sex life, what colors, textures, fabrics, and images would dominate the board?",
    "What is one thing you want me to do to your body tonight that you have thought about constantly but have never explicitly asked for out loud?",
    "How can we better transition from the stress of daily logistics, finances, and chores into a state of mutual erotic reception at the end of the day?",
    "If you could invent a brand new word to perfectly describe the unique flavor, intensity, and rhythm of our sexual chemistry, what would the word be?",
    "Looking back at this entire conversation we just had, what is the most surprising, exciting, or illuminating thing you learned about my desires today?"
  ],
  [CategoryType.SCENARIOS]: [
    "SCENARIO: We are driving late at night. I suddenly reach over, pull your hand to my lap, and look at you, clearly suggesting something. How do you react and where do we pull over?",
    "SCENARIO: We are at a secluded beach with absolutely no one around. The tide is rolling in, and we think we can sneak in a quick, thrilling encounter before we leave. What do we do and where do we hide?",
    "SCENARIO: What is a highly specific scenario or fantasy you've been harboring that you would like me to act out with you tonight? Walk me through how we start.",
    "ROLEPLAY: You are the patient coming in for a private checkup, and I am the professional doctor who is about to discover your symptoms are highly physical. How do we begin the examination?",
    "ROLEPLAY: We are acting out a teacher and student dynamic. You've stayed behind after class because you are failing my class, and you are willing to negotiate for a better grade. What is your opening line?",
    "ROLEPLAY: I am your severe boss, and you are my dedicated assistant. I lock the office door behind us after hours to go over some very \"private\" paperwork. Who initiates the first touch?",
    "SCENARIO: We are at a quiet dinner party with friends or family, and we are sitting next to each other under the table. One of us subtly slides their hand up the other's thigh while maintaining polite conversation. How do you keep from reacting?",
    "ROLEPLAY: You are a weary traveler checking into a boutique hotel late at night, and I am the playful receptionist who notices there is only one bed available—but offers you a very exclusive, private upgrade. How do we negotiate?",
    "SCENARIO: We are in a crowded, noisy elevator. We are pressed close together in the back corner. How do you quietly let me know you want me right now without anyone else noticing?",
    "SCENARIO: We are staying in a cabin with a large window looking out at a thunderstorm. We decide to discard all of our clothes and trace the rain on each other's bodies. Where do you touch me first?",
    "ROLEPLAY: I am a high-end personal massage therapist you hired for a private session in our living room, and you've requested the \"extra tension relief\" treatment. How do you guide my hands?",
    "SCENARIO: We are taking a warm, steamy bath or shower together after a very exhausting day. The water is running down our faces. Describe how you would slowly tease and touch me to wake my senses up.",
    "ROLEPLAY: You are a strict librarian who caught me whispering and misbehaving in the secluded back aisle. To keep me quiet, you have to find a highly physical way to muzzle me. What is your move?",
    "SCENARIO: We are at a public cinema, sitting in the very back row in the dark. The movie is loud. How do we sneakily find pleasure right there in our seats?",
    "ROLEPLAY: You are a modern royalty figure escaping the public eye for an evening, and I am your hired bodyguard who is secretly madly in love with you. We've just locked ourselves in a safehouse room.",
    "SCENARIO: I wake you up in the middle of the night, whispering that I can't sleep, and pull your warm body tightly against mine from behind. How do we turn this quiet moment into a slow, passionate encounter?",
    "ROLEPLAY: We are pretending to be absolute strangers meeting at a dimly lit hotel lounge. We must use fake names, make up eccentric backgrounds, and try to pick each other up. What is your opening line to me?",
    "SCENARIO: We are staying in a luxury hotel. One of us steps out of the bathroom wearing nothing but a loosely tied white towel and a playful smile. What happens next?",
    "ROLEPLAY: I am a personal trainer putting you through a highly intense, sweaty physical workout. You are completely exhausted and decide to distract me by pulling me down on the exercise mat. How do you do it?",
    "SCENARIO: We are at a crowded club or concert, and we've slipped away into a single-stall restroom for a quick, high-adrenaline tryst. We have exactly three minutes before someone knocks on the door. Go!",
    "ROLEPLAY: I am a wealthy photographer, and you are my gorgeous muse posing for a private portrait session. I ask you to let down your guard and shed a layer of clothing to capture your \"true essence.\"",
    "SCENARIO: We are cooking a romantic dinner together in the kitchen. I am standing at the stove, and you sneak up behind me, wrapping your arms around my waist and kissing my neck. What do you do to make me turn around?",
    "ROLEPLAY: One of us is a professional, confident dance instructor, and the other is a clumsy but enthusiastic student. We are practicing a slow, close, hip-to-hip tango in an empty studio.",
    "SCENARIO: We are caught in a sudden, torrential downpour while walking home and get completely soaked. We rush inside, shivering, and immediately start peeling off each other's wet clothes. How do we warm each other up?",
    "ROLEPLAY: You are the landlord coming to collect the overdue rent, and I am the tenant who is short on cash but has a highly creative alternative proposal to offer. Let's act out the negotiation.",
    "SCENARIO: We have a rare, completely free afternoon with no chores, phone notifications, or plans. We decide to spend the entire time naked under the sheets, playing, kissing, and exploring without checking the clock. What is our first game?",
    "ROLEPLAY: You are an undercover detective interrogating me in a dim room about a scandalous \"crime\" I committed. I refuse to speak unless you get extremely close and personal with me.",
    "SCENARIO: We are staying at a cozy bed-and-breakfast. The morning sun is just rising, and instead of going down for breakfast, you decide to serve me \"breakfast in bed\" using your body. Describe the menu."
  ],
  [CategoryType.DEEP_DIVE]: [
    "What is your biggest fear regarding our relationship?",
    "What is something you struggle to forgive, even if you want to?",
    "What is a past trauma that still affects how you love today?",
    "When was the last time you cried, and why?",
    "What is a deeply held belief you have that most people disagree with?",
    "What is the hardest lesson you've had to learn in life so far?",
    "If you had one week left to live, how would you spend it with me?",
    "What is something you are incredibly proud of but rarely talk about?",
    "How do you handle feelings of inadequacy or self-doubt?",
    "What does a 'meaningful life' look like to you?",
    "What is something youve always wanted to tell your partner you wanted to do but were to nervous?",
    "What is a deep-seated fear or lingering insecurity you hold regarding your own body or your sexual performance that you rarely discuss?",
    "Is there a physical act, routine, or position we currently engage in that you do not genuinely enjoy, but participate in because you believe it pleases me?",
    "When have you felt most sexually rejected or profoundly disconnected from me, and how can we handle mismatched desires more gracefully in the future?",
    "What does your ideal \"aftercare\" look like? What do you require emotionally and physically immediately after an intense, vulnerable sexual encounter?",
    "How do you handle internal feelings of sexual frustration when we go through a dry spell, and what can I do to help you feel cherished during those times?",
    "Is there a past sexual experience, trauma, or phase of your life that fundamentally shaped your current relationship with intimacy, for better or worse?",
    "What is the most vulnerable, submissive, or surrendered thing I could do during sex that would make you feel completely trusted and safe with me?",
    "Have you ever felt pressure to perform, endure pain, or exhibit a specific level of enthusiasm during sex when you were actually feeling physically or emotionally disconnected?",
    "What is a question about my sexual past, my bodily experiences, or my deepest desires that you have always wanted to ask, but were afraid of how I might react?",
    "How does emotional distance, stress from work, or conflict outside the bedroom affect your biological ability to experience physical arousal with me?",
    "What is a kinky, taboo, or unconventional concept that you are secretly drawn to psychologically, but feel too shy or ashamed to explore in physical reality?",
    "Have you ever faked an orgasm or exaggerated your pleasure with me? If so, what specific emotional need or fear were you trying to protect in that moment?",
    "What is a specific word, phrase, or action that instantly ruins the mood for you, acting as an immediate psychological and physical turn-off?",
    "How do you navigate the complex internal balance between wanting to feel fiercely, ravenously desired and wanting to feel deeply, tenderly respected?",
    "What is a small, unexpected turn-on, kink, or personal quirk you have discovered about your own evolving sexuality since we have been together?",
    "In what ways does your connection to your gender identity make you feel sexy, empowered, or conversely, constrained during our intimate moments?",
    "What is the hardest part about communicating a change in your sexual preferences, your boundaries, or your bodily autonomy to me?",
    "If you could write a highly honest letter of apology to your younger self regarding how you viewed sex and your body, what would the core message be?",
    "When you feel insecure about our physical connection or your desirability, what specific, actionable reassurance do you need from me to feel grounded again?"
  ],
  [CategoryType.CURIOUS_MINDS]: [
    "If you could design a quiet sanctuary for us anywhere in the universe, what would it look like and what would we do there?",
    "What is a belief or value you held tenaciously five years ago that you have completely outgrown today?",
    "If you could witness one private, mundane memory from my childhood as a silent observer, which age would you choose and why?",
    "What is a small, everyday struggle you face that you rarely talk about because you think it's too trivial?",
    "If you had to describe our connection as a physical landscape (e.g., a quiet library, a rugged peak, a sunlit meadow), what would it be?",
    "What is something you wish more people understood about your quiet moments or your silence?",
    "What is a piece of art, music, or literature that has fundamentally altered how you view the world?",
    "If we were characters in a vintage novel, what would be our recurring theme or central conflict?",
    "What is a lesson about love or friendship that you had to learn the hard way?",
    "If you could ask an all-knowing oracle one question about your own future, what would you ask?",
    "Which of your personality traits do you think is most often misunderstood by others, and how do I see it?",
    "If you could inherit a single memory from one of your ancestors, who would it be and what part of their life would you want to recall?",
    "What is a dream or project you've abandoned that you still think about with a quiet longing?",
    "In what ways do you think we balance or anchor each other's eccentricities?",
    "If our love story had a signature aroma (e.g., old books, petrichor, warm spices), what would it be?",
    "What is a question you wish people asked you more often instead of the standard 'how are you'?",
    "What is the most beautiful act of kindness you've ever witnessed, and how did it change your day?",
    "If you could speak to yourself at age sixteen for exactly sixty seconds, what truth would you urge them to accept?",
    "What is a tiny daily ritual or habit of mine that brings you an unexpected sense of comfort?",
    "If we were to create a 'time capsule' of our relationship today, what three unconventional items would you place inside?",
    "What is a fear about getting older that you are still trying to reconcile or make peace with?",
    "What is something you've done recently that made you feel proud of the person you are becoming?",
    "If you could spend a day conversing with anyone from history, who would it be and what would you discuss?",
    "What does 'home' mean to you in a single sentence, separate from a physical building?",
    "What is a hidden talent or weird obsession of yours that you haven't fully indulged yet?",
    "If our relationship had a secret, playful covenant or 'tenet,' what would be our golden rule?",
    "What is a specific emotion you struggle to articulate in words, and how do you show it instead?",
    "If you were given a chance to live in any fictional universe for a year, where would you go and what role would you play?",
    "What is the most intellectually stimulating conversation we've ever had, and why did it stick with you?",
    "What is a quality in me that you think will make me an incredible partner, friend, or guide in the years to come?",
    "If you could instantly acquire master-level expertise in one obscure branch of knowledge, what would you choose?",
    "What is a book or story from your childhood that left a permanent imprint on your imagination?",
    "In what ways do you think we are most similar, and in what ways are we beautifully different?",
    "What is a worry you carry that you feel entirely comfortable letting go of when we are together?",
    "If you had to choose a quiet hobby for us to practice in silence together, what would it be?",
    "What was a defining moment in your life where you had to make a choice that completely changed your trajectory?",
    "If you could curate a private museum of your life, what would be the centerpiece exhibit?",
    "What is a custom or tradition from another culture that you find incredibly beautiful and wish to adopt?",
    "What is a song that instantly evokes a specific, vivid memory of us, and what is that memory?",
    "If you could change one event in history without causing a paradox, what would you alter?",
    "What is a standard or expectation of society that you find completely absurd or exhausting?",
    "What is a personal mystery or question about the universe that you hope science solves in your lifetime?",
    "What does vulnerability feel like to you physically? Where do you carry that tension?",
    "If you could design a holiday that celebrates something small and mundane, what would we celebrate?",
    "What is something I did or said recently that made you think, 'I am so glad they are in my life'?",
    "What is a philosophy or piece of wisdom that you try to live by when things get chaotic?",
    "If you could travel back to the very first day we met, what secret advice would you whisper to your past self?",
    "What is a creative outlet you want to explore more deeply, and how can I help you clear the path for it?",
    "What is something you are holding onto that you think it might finally be time to let go of?",
    "If our relationship was a constellation, what would its name be and what story would it tell to stargazers?"
  ],
};
